In [3]:
from stt_toolkit import ResultCache

model_names = [
    "openai/whisper-large-v3-turbo",
    "whispercpp/large-v3-turbo",
    "bofenghuang/whisper-large-v3-distil-it-v0.2",
    "whispercpp/whisper-large-v3-distil-it-v0.2",
    "whispercpp/whisper-large-v3-distil-it-v0.2-q5_0",
]
tasks = ["lopozz/accenti_italiani[train]"]

cache = ResultCache("../results")
results = cache.load_results(
    models=model_names,
    tasks=tasks,
)

results.to_dataframe()

,task_name,model,speed,wer
0,lopozz/accenti_italiani[train],bofenghuang/whisper-large-v3-distil-it-v0.2,1x,0.136951
1,lopozz/accenti_italiani[train],openai/whisper-large-v3-turbo,1x,0.134132
2,lopozz/accenti_italiani[train],whispercpp/large-v3-turbo,1x,0.132018
3,lopozz/accenti_italiani[train],whispercpp/whisper-large-v3-distil-it-v0.2,1x,0.220343
4,lopozz/accenti_italiani[train],whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,1x,0.189100

In [4]:
from stt_toolkit import SpeedResultCache

model_names = [
    # "openai/whisper-large-v3-turbo",
    "bofenghuang/whisper-large-v3-distil-it-v0.2",
]

cache = SpeedResultCache("../results")
results = cache.load_results(models=model_names)
results.to_dataframe()

,task_name,model,audio_file,audio_length_s,requests,concurrency,avg_latency_s,rps,rtf,errors
0,None,bofenghuang/whisper-large-v3-distil-it-v0.2,data/network_1976/mad_as_hell.wav,78.6,5,1,1.1144,0.8972,70.5188,0

In [3]:
results

ResultCollection(results=[])