In [1]:
from stt_toolkit import ResultCache

model_names = [
    "openai/whisper-large-v3-turbo",
    "whispercpp/large-v3-turbo",
    "bofenghuang/whisper-large-v3-distil-it-v0.2",
    "whispercpp/whisper-large-v3-distil-it-v0.2",
    "whispercpp/whisper-large-v3-distil-it-v0.2-q5_0",
    "whispercpp/whisper-tiny-it-v1-ggml",
]
tasks = ["lopozz/accenti_italiani[train]"]

cache = ResultCache("../results")
results = cache.load_results(
    models=model_names,
    tasks=tasks,
)

results.to_dataframe()

                                             model speed       wer
0      bofenghuang/whisper-large-v3-distil-it-v0.2    1x  0.136951
1                    openai/whisper-large-v3-turbo    1x  0.134132
2                        whispercpp/large-v3-turbo    1x  0.132018
3       whispercpp/whisper-large-v3-distil-it-v0.2    1x  0.220343
4  whispercpp/whisper-large-v3-distil-it-v0.2-q5_0    1x  0.189100
5               whispercpp/whisper-tiny-it-v1-ggml    1x  0.402866

In [7]:
from stt_toolkit import SpeedResultCache

model_names = [
    # "openai/whisper-large-v3-turbo",
    "whispercpp/whisper-large-v3-distil-it-v0.2-q5_0",
]

cache = SpeedResultCache("../results")
results = cache.load_results(models=model_names)
results.to_dataframe()

,model,threads,processors,audio_length_s,avg_latency_s,avg_load_time_s,avg_total_time_s,rtf
0,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,2,1,78.6,151.7659,0.2124,151.9783,0.5179
1,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,2,2,78.6,66.5082,0.2141,66.7223,1.1818
2,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,2,4,78.6,63.5759,0.2269,63.8028,1.2363
3,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,4,1,78.6,75.8140,0.2173,76.0313,1.0367
4,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,4,2,78.6,35.4304,0.2162,35.6466,2.2184
5,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,4,4,78.6,42.2450,0.2229,42.4679,1.8606
6,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,6,1,78.6,52.1138,0.2136,52.3274,1.5082
7,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,6,2,78.6,31.1635,0.2156,31.3792,2.5222
8,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,8,1,78.6,32.3851,0.2235,32.6086,2.4270
9,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,8,2,78.6,27.9465,0.2187,28.1653,2.8125
10,whispercpp/whisper-large-v3-distil-it-v0.2-q5_0,8,3,78.6,23.6695,0.2192,23.8888,3.3207

In [2]:
results

ResultCollection(results=[])